use_frameworks!

target 'LiteData_Example' do

    pod 'LiteData', :path => '../'

    target 'LiteData_Tests' do
        inherit! :search_paths

        pod 'Quick', '~> 0.8'
        pod 'Nimble', '~> 3.0'
    end
end
